In [6]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [4]:
df = df.iloc[:, 2:]

In [5]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 0:2], df.iloc[:, -1], test_size=0.2, random_state=42)

In [53]:
print(type(X_train))
print(type(y_train))

<class 'numpy.ndarray'>
<class 'pandas.core.series.Series'>

In [7]:
X_train

     review education
12     Poor    School
4   Average        UG
37  Average        PG
8   Average        UG
3      Good        PG
6      Good    School
41     Good        PG
46     Poor        PG
47     Good        PG
15     Poor        UG
9      Good        UG
16     Poor        UG
24  Average        PG
34  Average    School
31     Poor    School
0   Average    School
44  Average        UG
27     Poor        PG
33     Good        PG
5   Average    School
29  Average        UG
11     Good        UG
36     Good        UG
1      Poor        UG
21  Average        PG
2      Good        PG
43     Poor        PG
35     Poor    School
23     Good    School
40     Good    School
10     Good        UG
22     Poor        PG
18     Good    School
49     Good        UG
20  Average    School
7      Poor    School
42     Good        PG
14     Poor        PG
28     Poor    School
38     Good    School

In [8]:
from sklearn.preprocessing import OrdinalEncoder

In [9]:
oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [ ]:
oe.categories_

# the reason for the error

# The reason is very subtle but important.
# You defined categories in the constructor, but the encoder is still not fitted.
# In scikit-learn, attributes ending with _ (like categories_, coef_, mean_) are created only 
# after fit() is called.

AttributeError: 'OrdinalEncoder' object has no attribute 'categories_'

In [11]:
oe.feature_names_in_

AttributeError: 'OrdinalEncoder' object has no attribute 'feature_names_in_'

### Attribute	Meaning
1. categories	-> What you provided manually
2. categories_	-> What the model learned during fit()

One more subtle ML detail

When you manually define categories, OrdinalEncoder will NOT learn new ones.

Example:

If test data contains "Excellent" → it will throw an error.

To handle this we often use:

OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)

In [13]:
# this is working 
oe.categories

[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']]

In [14]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [15]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [16]:
X_train

array([[0., 0.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.]])

In [17]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [18]:
oe.feature_names_in_

array(['review', 'education'], dtype=object)

In [19]:
oe.inverse_transform(np.array([0, 2]).reshape(1, 2))

array([['Poor', 'PG']], dtype=object)

In [20]:
oe.get_feature_names_out()

array(['review', 'education'], dtype=object)

In [21]:
oe.transform(np.array(['Poor', 'College']).reshape(1, 2))

c:\Users\v-guptaarpit\OneDrive - Microsoft\Documents\projects\Deep_Learning_NLP\venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

ValueError: Found unknown categories [np.str_('College')] in column 1 during transform

#### how to handle unknown values

In [22]:
oe = OrdinalEncoder(
    categories=[['Poor', 'Average', 'Excellent'], ['School', 'UG', 'PG']],
    handle_unknown='use_encoded_value',
    unknown_value=-1,
)

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, :2], df.iloc[:, -1], test_size=0.2, 
                                                    random_state=42)
X_train = oe.fit_transform(X_train)
oe.transform(np.array(['Poor', 'College']).reshape(1, 2))

c:\Users\v-guptaarpit\OneDrive - Microsoft\Documents\projects\Deep_Learning_NLP\venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[ 0., -1.]])

#### Handling infrequent (Rare) Categories

In [41]:
X = np.array([['dog'] * 5 + ['cat'] * 20 + ['rabbit'] * 10 + ['snake'] * 3 + ['horse'] * 2], dtype=object).T
X

array([['dog'],
       ['dog'],
       ['dog'],
       ['dog'],
       ['dog'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['snake'],
       ['snake'],
       ['snake'],
       ['horse'],
       ['horse']], dtype=object)

In [42]:
'''it sorts the categories by their frequencies and then picks the (max_categories-1) from the top
 and then combines the remaining which is going to the last category.
'''

enc = OrdinalEncoder(max_categories=3).fit(X)

In [43]:
enc.infrequent_categories_

[array(['dog', 'horse', 'snake'], dtype=object)]

In [44]:
enc.transform(np.array([['cat', 'rabbit', 'snake', 'dog', 'horse']]).reshape(5, 1))

array([[0.],
       [1.],
       [2.],
       [2.],
       [2.]])

In [47]:
''' 
only consider the categories which have frequency >= min_frequency
rest of them -> consider in others
'''

enc = OrdinalEncoder(min_frequency=4).fit(X)
enc.infrequent_categories_

[array(['horse', 'snake'], dtype=object)]

In [48]:
enc.transform(np.array([['cat', 'rabbit', 'snake', 'dog', 'horse']]).reshape(5, 1))

array([[0.],
       [2.],
       [3.],
       [1.],
       [3.]])

#### Deal with Missing Values

In [ ]:
# categorical data with missing values
data = [['Cat'], [np.nan], ['Dog'], ['Fish'], [np.nan]]

# setting encoded_missing_values to -1, indicating we want missing values to be encoded as -1
encoder = OrdinalEncoder(encoded_missing_value=-1)
encoded_data = encoder.fit_transform(data)
print(encoded_data)

[[ 0.]
 [nan]
 [ 1.]
 [ 2.]
 [nan]]

In [51]:
# or set it to np.nan
encoder = OrdinalEncoder(encoded_missing_value=np.nan)
encoded_data = encoder.fit_transform(data)
print(encoded_data)

[[ 0.]
 [nan]
 [ 1.]
 [ 2.]
 [nan]]

### Label Encoding

In [ ]:
## only for the label values, target feature.
# we cant use this for input/independent features.
# ideal only for ordinal target variables
''' 

1️⃣ Two Different Situations

You must always separate:

Case	Variable	Encoding
Feature column	X	Depends on data type
Target column	y	LabelEncoder

This is the main source of confusion.

2️⃣ Label Encoding for Ordinal Features (Correct)

If the categories have natural order, label encoding is appropriate.

Example:

Education Level
High School
Bachelor
Master
PhD


Encoding:

High School → 0
Bachelor    → 1
Master      → 2
PhD         → 3

This works because:

PhD > Master > Bachelor > High School

The numeric relationship reflects the real-world order.

For features we usually use:

OrdinalEncoder

Example:

from sklearn.preprocessing import OrdinalEncoder

enc = OrdinalEncoder()

X = [["High School"],["Bachelor"],["Master"],["PhD"]]

enc.fit_transform(X)
3️⃣ Label Encoding for Nominal Features (Wrong)

Nominal categories have no order.

Example:

Color
Red
Blue
Green

Label encoding produces:

Blue → 0
Green → 1
Red → 2

Now the model thinks:

Red > Green > Blue

Which is meaningless.

This introduces false numerical relationships.

Instead we use:

OneHotEncoder

Example:

Color_Red	Color_Blue	Color_Green
1	0	0
0	1	0
0	0	1

No ordering is introduced.

4️⃣ Label Encoding for Target Variable (Always OK)

Example classification target:

spam
ham
promotion

Label encoding:

ham → 0
promotion → 1
spam → 2

This does NOT create ordering issues because the model treats them as class IDs.

The number is just an index.

Example:

class 0
class 1
class 2

Most sklearn models expect integer class labels, which is why LabelEncoder exists.

5️⃣ Simple Rule Used in ML
Data Type	Encoder
Nominal feature	OneHotEncoder
Ordinal feature	OrdinalEncoder
Target labels	LabelEncoder
6️⃣ Important Interview Point

Many people say:

"LabelEncoder is used for ordinal data."

This is partially incorrect.

Correct statement:

LabelEncoder is designed for target labels.
OrdinalEncoder is used for ordinal features.
7️⃣ Quick Visual Summary
Variable	Example	Encoder
City	Delhi, Mumbai, Chennai	OneHotEncoder
Education	Bachelor, Master, PhD	OrdinalEncoder
Target	spam, ham	LabelEncoder

✅ Final answer

Label encoding is:

appropriate for ordinal data (features)

appropriate for target labels

not appropriate for nominal features
'''
# not appropriate for nominal data/ incorrect. should never be used.
# Label Encoding for Target Variable (Always OK)

from sklearn.preprocessing import LabelEncoder

In [55]:
le = LabelEncoder()

In [56]:
le.fit(y_train)

LabelEncoder()

In [57]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [58]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [59]:
y_train

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0])

In [60]:
le.inverse_transform([1, 1, 0])

array(['Yes', 'Yes', 'No'], dtype=object)

### One Hot Encoder

In [71]:
cars = pd.read_csv('cars.csv').drop(columns=['km_driven', 'owner'])
cars.head()

     brand    fuel  selling_price
0   Maruti  Diesel         450000
1    Skoda  Diesel         370000
2    Honda  Petrol         158000
3  Hyundai  Diesel         225000
4   Maruti  Petrol         130000

In [72]:
# here both 'brand' and 'fuel' are nominal categorical data

X = cars.iloc[:, 0:2]
y = cars.iloc[:, -1]

In [73]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [74]:
X_train

         brand    fuel
6518      Tata  Petrol
6144     Honda  Petrol
6381   Hyundai  Diesel
438     Maruti  Diesel
5939    Maruti  Petrol
...        ...     ...
5226  Mahindra  Diesel
5390    Maruti  Diesel
860    Hyundai  Petrol
7603    Maruti  Diesel
7270    Maruti  Petrol

[6502 rows x 2 columns]

In [75]:
y_train

6518    520000
6144    300000
6381    380000
438     530000
5939    335000
         ...
5226    475000
5390    530000
860     576000
7603    770000
7270    155000
Name: selling_price, Length: 6502, dtype: int64

In [76]:
print(X_train['brand'].nunique())
print(X_train['fuel'].nunique())

32
4

In [77]:
from sklearn.preprocessing import OneHotEncoder

In [78]:
ohe = OneHotEncoder()

In [79]:
ohe.fit_transform(X_train)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 13004 stored elements and shape (6502, 36)>

In [80]:
X_train.shape

(6502, 2)

In [81]:
X_train = ohe.fit_transform(X_train).toarray()
X_train

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(6502, 36))

In [82]:
X_train.shape

(6502, 36)

In [83]:
ohe.categories_

[array(['Ambassador', 'Ashok', 'Audi', 'BMW', 'Chevrolet', 'Daewoo',
        'Datsun', 'Fiat', 'Force', 'Ford', 'Honda', 'Hyundai', 'Isuzu',
        'Jaguar', 'Jeep', 'Kia', 'Land', 'Lexus', 'MG', 'Mahindra',
        'Maruti', 'Mercedes-Benz', 'Mitsubishi', 'Nissan', 'Opel',
        'Peugeot', 'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen',
        'Volvo'], dtype=object),
 array(['CNG', 'Diesel', 'LPG', 'Petrol'], dtype=object)]

In [84]:
ohe.feature_names_in_

array(['brand', 'fuel'], dtype=object)

In [85]:
ohe.n_features_in_

2

In [86]:
ohe.get_feature_names_out()

array(['brand_Ambassador', 'brand_Ashok', 'brand_Audi', 'brand_BMW',
       'brand_Chevrolet', 'brand_Daewoo', 'brand_Datsun', 'brand_Fiat',
       'brand_Force', 'brand_Ford', 'brand_Honda', 'brand_Hyundai',
       'brand_Isuzu', 'brand_Jaguar', 'brand_Jeep', 'brand_Kia',
       'brand_Land', 'brand_Lexus', 'brand_MG', 'brand_Mahindra',
       'brand_Maruti', 'brand_Mercedes-Benz', 'brand_Mitsubishi',
       'brand_Nissan', 'brand_Opel', 'brand_Peugeot', 'brand_Renault',
       'brand_Skoda', 'brand_Tata', 'brand_Toyota', 'brand_Volkswagen',
       'brand_Volvo', 'fuel_CNG', 'fuel_Diesel', 'fuel_LPG',
       'fuel_Petrol'], dtype=object)

In [87]:
X_train

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(6502, 36))

In [88]:
pd.DataFrame(X_train, columns=ohe.get_feature_names_out())

,brand_Ambassador,brand_Ashok,brand_Audi,brand_BMW,brand_Chevrolet,brand_Daewoo,brand_Datsun,brand_Fiat,brand_Force,brand_Ford,...,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,brand_Volvo,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6497,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6498,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6499,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
6500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6501,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [112]:
'''
| Setting | Output        |
| ------- | ------------- |
| `True`  | sparse matrix |
| `False` | numpy array   |

1️⃣ What sparse_output=True means

When you run One-Hot Encoding, most values become 0.

Example categorical column:

Fuel
Petrol
Diesel
Petrol

After OHE:

Petrol	Diesel
1	0
0	1
1	0

Most values are 0.

A sparse matrix stores only the non-zero values.

Instead of storing:

[1,0]
[0,1]
[1,0]

it stores something like:

(0,0) -> 1
(1,1) -> 1
(2,0) -> 1

This saves a huge amount of memory.

So if:

OneHotEncoder(sparse_output=True)

the output will be a scipy sparse matrix.

Type:

scipy.sparse.csr_matrix
2️⃣ What sparse_output=False means

Now sklearn returns a normal NumPy array.

Example:

[[1. 0.]
 [0. 1.]
 [1. 0.]]

Type:

numpy.ndarray
'''

'\n| Setting | Output        |\n| ------- | ------------- |\n| `True`  | sparse matrix |\n| `False` | numpy array   |\n\n1️⃣ What sparse_output=True means\n\nWhen you run One-Hot Encoding, most values become 0.\n\nExample categorical column:\n\nFuel\nPetrol\nDiesel\nPetrol\n\nAfter OHE:\n\nPetrol\tDiesel\n1\t0\n0\t1\n1\t0\n\nMost values are 0.\n\nA sparse matrix stores only the non-zero values.\n\nInstead of storing:\n\n[1,0]\n[0,1]\n[1,0]\n\nit stores something like:\n\n(0,0) -> 1\n(1,1) -> 1\n(2,0) -> 1\n\nThis saves a huge amount of memory.\n\nSo if:\n\nOneHotEncoder(sparse_output=True)\n\nthe output will be a scipy sparse matrix.\n\nType:\n\nscipy.sparse.csr_matrix\n2️⃣ What sparse_output=False means\n\nNow sklearn returns a normal NumPy array.\n\nExample:\n\n[[1. 0.]\n [0. 1.]\n [1. 0.]]\n\nType:\n\nnumpy.ndarray\n'

In [113]:
'''
3️⃣ Why your X_train.shape didn't change

You wrote:

ohe.fit_transform(X_train)

But you didn't store the result.

OneHotEncoder does NOT modify data in-place.

It returns a new matrix.

Your code effectively did this:

transform X_train → produce encoded matrix → throw it away

So X_train stays the same.

X_train.shape = (6502,2)

because you never replaced it.

4️⃣ Correct way

You must store it:

X_train_encoded = ohe.fit_transform(X_train)

Now check shape:

X_train_encoded.shape

Example result:

(6502, 4)

because categories expand into multiple columns.
'''

"\n3️⃣ Why your X_train.shape didn't change\n\nYou wrote:\n\nohe.fit_transform(X_train)\n\nBut you didn't store the result.\n\nOneHotEncoder does NOT modify data in-place.\n\nIt returns a new matrix.\n\nYour code effectively did this:\n\ntransform X_train → produce encoded matrix → throw it away\n\nSo X_train stays the same.\n\nX_train.shape = (6502,2)\n\nbecause you never replaced it.\n\n4️⃣ Correct way\n\nYou must store it:\n\nX_train_encoded = ohe.fit_transform(X_train)\n\nNow check shape:\n\nX_train_encoded.shape\n\nExample result:\n\n(6502, 4)\n\nbecause categories expand into multiple columns.\n"

### Dummy Variable Trap -> Drop One Columns (generally the 1st one)

In [89]:
cars = pd.read_csv('cars.csv').drop(columns=['km_driven', 'owner'])
cars.head()

     brand    fuel  selling_price
0   Maruti  Diesel         450000
1    Skoda  Diesel         370000
2    Honda  Petrol         158000
3  Hyundai  Diesel         225000
4   Maruti  Petrol         130000

In [90]:
# here both 'brand' and 'fuel' are nominal categorical data

X = cars.iloc[:, 0:2]
y = cars.iloc[:, -1]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

'''
dropping the 1st columns -> usually needed in linear algorithms
'''

ohe = OneHotEncoder(drop='first', sparse_output=False)
ohe.fit_transform(X_train).shape

(6502, 34)

In [98]:
'''
thats why the shape is now 6503 X 34, 1 column has been dropped from each of the feature variables i.e., brand and fuel
'''

'\nthats why the shape is now 6503 X 34, 1 column has been dropped from each of the feature variables i.e., brand and fuel\n'

In [101]:
#handling rare_categories

X_train['brand'].value_counts()

brand
Maruti           1953
Hyundai          1127
Mahindra          635
Tata              586
Toyota            391
Honda             369
Ford              320
Chevrolet         185
Renault           183
Volkswagen        154
BMW                96
Skoda              82
Nissan             62
Jaguar             59
Volvo              54
Datsun             48
Mercedes-Benz      43
Fiat               35
Audi               30
Jeep               26
Lexus              22
Mitsubishi         13
Force               6
Land                5
Kia                 4
Ambassador          3
MG                  3
Daewoo              3
Isuzu               2
Ashok               1
Peugeot             1
Opel                1
Name: count, dtype: int64

In [100]:
X_train['fuel'].value_counts()

fuel
Diesel    3545
Petrol    2880
CNG         46
LPG         31
Name: count, dtype: int64

In [102]:
## using Min Frequency

'''
all the categories having freq less than 100 will fall into others
'''

ohe = OneHotEncoder(sparse_output=False, min_frequency=100)
ohe.fit_transform(X_train).shape

(6502, 14)

In [103]:
ohe.get_feature_names_out()

array(['brand_Chevrolet', 'brand_Ford', 'brand_Honda', 'brand_Hyundai',
       'brand_Mahindra', 'brand_Maruti', 'brand_Renault', 'brand_Tata',
       'brand_Toyota', 'brand_Volkswagen', 'brand_infrequent_sklearn',
       'fuel_Diesel', 'fuel_Petrol', 'fuel_infrequent_sklearn'],
      dtype=object)

In [ ]:
## using max_categories

ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore', max_categories=15)
ohe.fit_transform(X_train).shape

# 15 max categories from brand and 4 < 15 from fuel

(6502, 19)

In [110]:
# how to handle unknown category 

'''
here it will give just error, simple straightforward
'''

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

ohe = OneHotEncoder(drop='first', sparse_output=False)
ohe.fit_transform(X_train)

ohe.transform(np.array(['local', 'Petrol']).reshape(1, 2))

/Users/arpitgupta/Documents/Deep_Learning_NLP/venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

ValueError: Found unknown categories [np.str_('local')] in column 0 during transform

In [111]:
'''
this is the other option, we can just simply ignore
'''

ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
ohe.fit_transform(X)

ohe.transform(np.array(['local', 'Petrol']).reshape(1, 2))

/Users/arpitgupta/Documents/Deep_Learning_NLP/venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1.]])

### High number of Catagories -> High Cadinality -> Just for a Note

# Label Binarizer

In [114]:
'''
When we need to apply OHE on the output column
'''

'\nWhen we need to apply OHE on the output column\n'

In [119]:
from sklearn.preprocessing import LabelBinarizer

# Example multi class label
y = ['cat', 'dog', 'fish', 'dog', 'cat']

# Initialize LabelBinarizer
lb = LabelBinarizer()

# Fit and transform the target variable
y_binarized = lb.fit_transform(y)

print("Binarized variables:\n", y_binarized)

# Inverse transform to recover original labels
y_original = lb.inverse_transform(y_binarized)

print("Original labels:\n", y_original)

Binarized variables:
 [[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]]
Original labels:
 ['cat' 'dog' 'fish' 'dog' 'cat']

### Multi-Label Classification

In [120]:
from sklearn.preprocessing import MultiLabelBinarizer

# Example multi-label data
y = [('red', 'blue'), ('blue', 'green'), ('green',), ('red',)]

# Initialize MultiLabelBinarizer
mlb = MultiLabelBinarizer()

# Fit and transform the data to binary matrix format
Y = mlb.fit_transform(y)

print("Binary matrix:\n", Y)
print("Class labels:", mlb.classes_)

# Inverse transform to recover original labels
y_inv = mlb.inverse_transform(Y)
print("Inverse transformed labels:", y_inv)

Binary matrix:
 [[1 0 1]
 [1 1 0]
 [0 1 0]
 [0 0 1]]
Class labels: ['blue' 'green' 'red']
Inverse transformed labels: [('blue', 'red'), ('blue', 'green'), ('green',), ('red',)]