In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [4]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(, test_size=0.2)

### 3. Count Encoder/Frequency Encoder

In [37]:
!pip install category_encoders==2.7.0

Requirement already satisfied: category_encoders==2.7.0 in c:\users\v-guptaarpit\onedrive - microsoft\documents\projects\deep_learning_nlp\venv\lib\site-packages (2.7.0)
Requirement already satisfied: numpy>=1.14.0 in c:\users\v-guptaarpit\onedrive - microsoft\documents\projects\deep_learning_nlp\venv\lib\site-packages (from category_encoders==2.7.0) (1.26.4)
Requirement already satisfied: pandas>=1.0.5 in c:\users\v-guptaarpit\onedrive - microsoft\documents\projects\deep_learning_nlp\venv\lib\site-packages (from category_encoders==2.7.0) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in c:\users\v-guptaarpit\onedrive - microsoft\documents\projects\deep_learning_nlp\venv\lib\site-packages (from category_encoders==2.7.0) (1.0.2)
Requirement already satisfied: scikit-learn<1.6.0,>=1.0.0 in c:\users\v-guptaarpit\onedrive - microsoft\documents\projects\deep_learning_nlp\venv\lib\site-packages (from category_encoders==2.7.0) (1.5.2)
Requirement already satisfied: scipy>=1.0.0 in c:\users\v-guptaarpit\onedrive - microsoft\documents\projects\deep_learning_nlp\venv\lib\site-packages (from category_encoders==2.7.0) (1.15.3)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\v-guptaarpit\onedrive - microsoft\documents\projects\deep_learning_nlp\venv\lib\site-packages (from category_encoders==2.7.0) (0.14.6)
Requirement already satisfied: joblib>=1.2.0 in c:\users\v-guptaarpit\onedrive - microsoft\documents\projects\deep_learning_nlp\venv\lib\site-packages (from scikit-learn<1.6.0,>=1.0.0->category_encoders==2.7.0) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\v-guptaarpit\onedrive - microsoft\documents\projects\deep_learning_nlp\venv\lib\site-packages (from scikit-learn<1.6.0,>=1.0.0->category_encoders==2.7.0) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\v-guptaarpit\onedrive - microsoft\documents\projects\deep_learning_nlp\venv\lib\site-packages (from pandas>=1.0.5->category_encoders==2.7.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\v-guptaarpit\onedrive - microsoft\documents\projects\deep_learning_nlp\venv\lib\site-packages (from pandas>=1.0.5->category_encoders==2.7.0) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\v-guptaarpit\onedrive - microsoft\documents\projects\deep_learning_nlp\venv\lib\site-packages (from pandas>=1.0.5->category_encoders==2.7.0) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\v-guptaarpit\onedrive - microsoft\documents\projects\deep_learning_nlp\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders==2.7.0) (1.17.0)
Requirement already satisfied: packaging>=21.3 in c:\users\v-guptaarpit\onedrive - microsoft\documents\projects\deep_learning_nlp\venv\lib\site-packages (from statsmodels>=0.9.0->category_encoders==2.7.0) (24.2)

In [47]:
# dataset generation
import pandas as pd
import numpy as np
import category_encoders as ce

# Simulating a dataset
data = {
    'Age': np.random.randint(20, 60, size=100).astype(float),  # Random ages between 20 and 60
    'State': np.random.choice(['Karnataka', 'Tamil Nadu', 'Maharashtra', 'Delhi', 'Telangana'], size=100),
    'Education': np.random.choice(['High School', 'UG', 'PG'], size=100),
    'Package': np.random.rand(100) * 100  # Random package values for demonstration
}

# Introducing missing values in 'Age' column (5%)
np.random.seed(0)  # For reproducibility
missing_indices = np.random.choice(data['Age'].shape[0], replace=False, size=int(data['Age'].shape[0] * 0.05))
data['Age'][missing_indices] = np.nan

df = pd.DataFrame(data)
df.head()

    Age       State    Education    Package
0  54.0  Tamil Nadu  High School  40.612049
1  49.0       Delhi           PG  56.921076
2   NaN   Telangana  High School  34.360550
3  54.0       Delhi           PG  78.887278
4  33.0       Delhi           PG  41.137241

In [48]:
print(type(df['State'].value_counts()))

<class 'pandas.core.series.Series'>

In [49]:
df['State'].value_counts()

State
Tamil Nadu     23
Delhi          23
Karnataka      20
Telangana      18
Maharashtra    16
Name: count, dtype: int64

In [50]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Package']), df['Package'], test_size=0.2, random_state=42)

In [51]:
X_train.head()

     Age        State    Education
55   NaN   Tamil Nadu  High School
88  42.0  Maharashtra           PG
26   NaN  Maharashtra           PG
42  39.0        Delhi           PG
69  33.0        Delhi  High School

In [56]:
X_train['State'].value_counts()

State
Delhi          18
Tamil Nadu     17
Telangana      17
Maharashtra    14
Karnataka      14
Name: count, dtype: int64

In [52]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.base import BaseEstimator, TransformerMixin
import pandas as pd
import sklearn

In [53]:
class CountEncoder(BaseEstimator, TransformerMixin):
    def __init__(self, columns=None):
        self.columns = columns
        self.count_map = {}

    def fit(self, X, y=None):
        if self.columns is None:
            self.columns = X.columns
        for col in self.columns:
            self.count_map[col] = X[col].value_counts().to_dict()
        return self
    
    def transform(self, X):
        X = X.copy()
        for col in self.columns:
            X[col] = X[col].map(self.count_map[col]).fillna(0)
        return X

In [57]:
preprocessor = ColumnTransformer(
    transformers=([
        ('age_missing', SimpleImputer(strategy='mean'), ['Age']),
        ('cat_state', CountEncoder(), ['State']),
        ('education_ordinal', OrdinalEncoder(), ['Education'])
    ])
)

sklearn.set_config(transform_output='pandas')   # just so we can get the output in pandas

In [58]:
preprocessor.fit_transform(X_train)

    age_missing__Age  cat_state__State  education_ordinal__Education
55         38.666667                17                           0.0
88         42.000000                14                           1.0
26         38.666667                14                           1.0
42         39.000000                18                           1.0
69         33.000000                18                           0.0
..               ...               ...                           ...
60         45.000000                17                           0.0
71         44.000000                17                           0.0
14         50.000000                14                           2.0
92         31.000000                14                           2.0
51         23.000000                17                           0.0

[80 rows x 3 columns]

### 4. Frequency Encoder

In [ ]:
"""
For Frequency Encoding, just make this 'normalize=True' in CountEncoder

preprocessor = ColumnTransformer(
    transformers=([
        ('age_missing', SimpleImputer(strategy='mean'), ['Age']),
        ('cat_state', CountEncoder(normalize=True), ['State']),
        ('education_ordinal', OrdinalEncoder(), ['Education'])
    ])
)

sklearn.set_config(transform_output='pandas')   # just so we can get the output in pandas
"""

In [60]:
preprocessor = ColumnTransformer(
    transformers=[
        ('age_missing', SimpleImputer(strategy='mean'), ['Age']),
        ('cat_state', CountEncoder(normalize=True), ['State']),
        ('education_ordinal', OrdinalEncoder(), ['Education'])
    ])
sklearn.set_config(transform_output="pandas")

In [61]:
preprocessor.fit_transform(X_train)

    age_missing__Age  cat_state__State  education_ordinal__Education
55         38.666667            0.2125                           0.0
88         42.000000            0.1750                           1.0
26         38.666667            0.1750                           1.0
42         39.000000            0.2250                           1.0
69         33.000000            0.2250                           0.0
..               ...               ...                           ...
60         45.000000            0.2125                           0.0
71         44.000000            0.2125                           0.0
14         50.000000            0.1750                           2.0
92         31.000000            0.1750                           2.0
51         23.000000            0.2125                           0.0

[80 rows x 3 columns]

### Now Using Category Encoders

In [59]:
# using category encoders
from category_encoders.count import CountEncoder

In [68]:
# parameters
import pandas as pd
import numpy as np
import category_encoders as ce

# Simulating a dataset
np.random.seed(42)  # For reproducibility
data = {
    'State': np.random.choice(['Karnataka', 'Tamil Nadu', 'Maharashtra', 'Delhi', 'Telangana', np.NaN], dtype=object, size=100),
    'Education': np.random.choice(['High School', 'UG', 'PG', np.NaN], dtype=object, size=100)
}
df = pd.DataFrame(data)

df.head(5)

TypeError: choice() got an unexpected keyword argument 'dtype'

In [ ]:
''' this one will work, in the above errored out code, NumPy wants one uniform type, 
so it converts the whole thing to something like
array(['Karnataka', 'Tamil Nadu', 'Maharashtra', 'Delhi', 'Telangana', 'nan'], dtype='<U...')
'''

### Please go through this link: Very Important
https://chatgpt.com/share/69c24f8f-f400-8008-9a17-731992d593e3

In [71]:
import pandas as pd
import numpy as np

np.random.seed(42)

state_choices = np.array(
    ['Karnataka', 'Tamil Nadu', 'Maharashtra', 'Delhi', 'Telangana', np.nan],
    dtype=object
)

education_choices = np.array(
    ['High School', 'UG', 'PG', np.nan],
    dtype=object
)

data = {
    'State': np.random.choice(state_choices, size=100),
    'Education': np.random.choice(education_choices, size=100)
}

df = pd.DataFrame(data)

In [72]:
df.isnull().sum()

State        17
Education    23
dtype: int64

In [76]:
# Initialize the CountEncoder with various parameters

encoder = ce.CountEncoder(
    cols=['State', 'Education'],
    handle_missing='value',     # Treat NaNs as a separate/countable category
    handle_unknown='error',     #Treat unknown categories as NaNs (if seen during transformation not fit)
)

In [77]:
# Fit and transform the dataset

encoded_df = encoder.fit_transform(df)
print(encoded_df.head(5))

   State  Education
0     25         34
1     17         27
2     11         27
3     17         27
4     17         34

In [ ]:
'''
We have 3 options for
handle_missing = 
1. 'value' -> treat np.nan/missing values at separate category.
2. 'return nan' -> dont encode the missing values, just return them as it is.
3. 'error' -> if our dataframe has missing values, it wil get errored out. 


Handle_unknown -> lets say, we trained/ fitted the data on 5 different categories but at the time of 
transformation, we get some unseen value which has never been seen before during fitting/ training.
here we also have multiple option:-

1. 'error' -> throw error, simply.
2. 'return_nan' -> return nan instead of those categories
3. 'value' -> assign them new category, most probably, it will return zero because their frequency will 
obviously be zero.
'''

In [66]:
encoder.mapping

{'State': State
 Delhi          25
 Tamil Nadu     19
 Telangana      17
 nan            17
 Maharashtra    11
 Karnataka      11
 Name: count, dtype: int64,
 'Education': Education
 PG             34
 High School    27
 nan            23
 UG             16
 Name: count, dtype: int64}

In [ ]:
# this will throw error -> as we set the handle_unknown = 'error'

new_data = pd.DataFrame({'State': ['Bihar'], 'Education': ['UG']})

encoder.transform(new_data)

ValueError: Missing data found in column State at transform time.

In [86]:
import numpy as np
import pandas as pd

np.random.seed(0)

choices = np.array(['A', 'B', 'C', 'D', 'E', 'F', np.nan], dtype=object)

data = {
    'Category': np.random.choice(
        choices,
        size=100,
        p=[0.3, 0.25, 0.15, 0.15, 0.05, 0.05, 0.05]
    ),
    'Value': np.random.rand(100)
}

df = pd.DataFrame(data)

print(df.isnull().sum())
df.sample(10)

Category    5
Value       0
dtype: int64

   Category     Value
91        C  0.209844
29        B  0.290078
2         C  0.735194
50        C  0.149448
44        C  0.806194
78        A  0.704414
33        C  0.298282
65        B  0.855803
75        A  0.223925
45        C  0.703889

In [84]:
df.isnull().sum()

Category    5
Value       0
dtype: int64

In [85]:
df['Category'].value_counts()

Category
A    34
B    22
C    21
D    12
F     4
E     2
Name: count, dtype: int64

In [ ]:
encoder = ce.CountEncoder(
    cols=['category'],
    min_group_size=5,       # Groups with counts less than 5 will be combined, so all the rare categories
    # combined into 1 category
    # min_group_name = 'salman'
)

# Fit and transform the dataset
encoded_df = encoder.fit_transform(df['Category'])

# Display the original and encoded data for comparison

In [1]:
import numpy as np