In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.model_selection import train_test_split

In [30]:
df = pd.read_csv('cars.csv')

In [31]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [32]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [33]:
X_train, X_test, y_train, y_test = train_test_split(
    df.drop(columns=['selling_price']),
    df['selling_price'],
    test_size=0.2,
    random_state=42
)

In [34]:
X_train

         brand  km_driven    fuel                 owner
6518      Tata       2560  Petrol           First Owner
6144     Honda      80000  Petrol          Second Owner
6381   Hyundai     150000  Diesel  Fourth & Above Owner
438     Maruti     120000  Diesel          Second Owner
5939    Maruti      25000  Petrol           First Owner
...        ...        ...     ...                   ...
5226  Mahindra     120000  Diesel           First Owner
5390    Maruti      80000  Diesel          Second Owner
860    Hyundai      35000  Petrol           First Owner
7603    Maruti      27000  Diesel           First Owner
7270    Maruti      70000  Petrol          Second Owner

[6502 rows x 4 columns]

In [35]:
oe = OrdinalEncoder(categories=[['Test Drive Car', 'Fourth & Above Owner', 'Third Owner', 'Second Owner', 'First Owner']])

X_train_owner = oe.fit_transform(X_train.loc[:, ['owner']])
X_test_owner = oe.transform(X_test.loc[:, ['owner']])

In [36]:
X_train_owner

array([[4.],
       [3.],
       [1.],
       ...,
       [4.],
       [4.],
       [3.]], shape=(6502, 1))

In [37]:
# convert to DF

X_train_owner_df = pd.DataFrame(X_train_owner, columns=oe.get_feature_names_out())
X_test_owner_df = pd.DataFrame(X_test_owner, columns=oe.get_feature_names_out())

In [38]:
X_train_owner_df.head()

   owner
0    4.0
1    3.0
2    1.0
3    3.0
4    4.0

In [39]:
# apply ohe to brand and fuel column

ohe = OneHotEncoder(sparse_output=False)

X_train_brand_fuel = ohe.fit_transform(X_train[['brand', 'fuel']])
X_test_brand_fuel = ohe.transform(X_test[['brand', 'fuel']])

In [40]:
# converting to dataframe

X_train_brand_fuel_df = pd.DataFrame(X_train_brand_fuel, columns=ohe.get_feature_names_out())
X_test_brand_fuel_df = pd.DataFrame(X_test_brand_fuel, columns=ohe.get_feature_names_out())

In [41]:
X_train_brand_fuel_df.head()

,brand_Ambassador,brand_Ashok,brand_Audi,brand_BMW,brand_Chevrolet,brand_Daewoo,brand_Datsun,brand_Fiat,brand_Force,brand_Ford,...,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,brand_Volvo,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [42]:
X_train.head()

        brand  km_driven    fuel                 owner
6518     Tata       2560  Petrol           First Owner
6144    Honda      80000  Petrol          Second Owner
6381  Hyundai     150000  Diesel  Fourth & Above Owner
438    Maruti     120000  Diesel          Second Owner
5939   Maruti      25000  Petrol           First Owner

In [43]:
X_train_rem = X_train.drop(columns=['brand', 'fuel', 'owner'], inplace=True)
X_test_rem = X_test.drop(columns=['brand', 'fuel', 'owner'], inplace=True)

In [46]:
X_test_rem

In [44]:
X_train.head()

      km_driven
6518       2560
6144      80000
6381     150000
438      120000
5939      25000

In [47]:
X_train = pd.concat([X_train, X_train_owner_df, X_train_brand_fuel_df], axis=1)
X_test = pd.concat([X_test, X_test_owner_df, X_test_brand_fuel_df], axis=1)

In [49]:
X_train.head()

,km_driven,owner,brand_Ambassador,brand_Ashok,brand_Audi,brand_BMW,brand_Chevrolet,brand_Daewoo,brand_Datsun,brand_Fiat,...,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,brand_Volvo,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol
6518,2560.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6144,80000.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6381,150000.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
438,120000.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5939,25000.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

# The Easy Way -> Using Column Transformer

In [4]:
from sklearn.compose import ColumnTransformer

In [51]:
df = pd.read_csv('cars.csv')

In [52]:
X_train, X_test, y_train, y_test = train_test_split(
    df.drop(columns=['selling_price']),
    df['selling_price'],
    test_size=0.2,
    random_state=42
)

In [53]:
X_train.head()

        brand  km_driven    fuel                 owner
6518     Tata       2560  Petrol           First Owner
6144    Honda      80000  Petrol          Second Owner
6381  Hyundai     150000  Diesel  Fourth & Above Owner
438    Maruti     120000  Diesel          Second Owner
5939   Maruti      25000  Petrol           First Owner

In [ ]:
transformer = ColumnTransformer(
    [
        ("ordinal", OrdinalEncoder(categories=[['Test Drive Car', 'Fourth & Above Owner', 'Third Owner', 'Second Owner', 'First Owner']]), ['owner']),
        ("onehot", OneHotEncoder(sparse_output=False), ['brand', 'fuel'])
    ],
    remainder='passthrough'
)

# setting to get pandas dataframe, without this, we were getting numpy array earlier.
transformer.set_output(transform='pandas')

'''
ColumnTransformer(
    [("operation_name", object, [col1, col2, .....]), (), ()]
)

operation_name -> whatevr we want to give, our choice. whatever we want to call that operation/transformation
'''

'\nColumnTransformer(\n    [("operation_name", object, [col1, col2, .....]), (), ()]\n)\n\noperation_name -> whatevr we want to give, our choice. whatever we want to call that operation/transformation\n'

In [58]:
# giving full data, X_train and X_test

X_train_transformed = transformer.fit_transform(X_train)
X_test_transformer = transformer.transform(X_test)

In [59]:
X_train_transformed

,ordinal__owner,onehot__brand_Ambassador,onehot__brand_Ashok,onehot__brand_Audi,onehot__brand_BMW,onehot__brand_Chevrolet,onehot__brand_Daewoo,onehot__brand_Datsun,onehot__brand_Fiat,onehot__brand_Force,...,onehot__brand_Skoda,onehot__brand_Tata,onehot__brand_Toyota,onehot__brand_Volkswagen,onehot__brand_Volvo,onehot__fuel_CNG,onehot__fuel_Diesel,onehot__fuel_LPG,onehot__fuel_Petrol,remainder__km_driven
6518,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2560
6144,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,80000
6381,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,150000
438,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,120000
5939,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,25000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5226,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,120000
5390,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,80000
860,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,35000
7603,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,27000
7270,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,70000

In [ ]:
'''
not needed anymore
using this -> transformer.set_output(transform='pandas') now.
we will directly get a pandas dataframe, no need to convert from numpy array.
'''

# pd.DataFrame(X_train_transformed, columns=transformer.get_feature_names_out())

,ordinal__owner,onehot__brand_Ambassador,onehot__brand_Ashok,onehot__brand_Audi,onehot__brand_BMW,onehot__brand_Chevrolet,onehot__brand_Daewoo,onehot__brand_Datsun,onehot__brand_Fiat,onehot__brand_Force,...,onehot__brand_Skoda,onehot__brand_Tata,onehot__brand_Toyota,onehot__brand_Volkswagen,onehot__brand_Volvo,onehot__fuel_CNG,onehot__fuel_Diesel,onehot__fuel_LPG,onehot__fuel_Petrol,remainder__km_driven
0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2560.0
1,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,80000.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,150000.0
3,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,120000.0
4,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,25000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6497,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,120000.0
6498,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,80000.0
6499,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,35000.0
6500,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,27000.0
6501,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,70000.0

In [64]:
transformer.feature_names_in_

array(['brand', 'km_driven', 'fuel', 'owner'], dtype=object)

In [65]:
transformer.get_feature_names_out()

array(['ordinal__owner', 'onehot__brand_Ambassador',
       'onehot__brand_Ashok', 'onehot__brand_Audi', 'onehot__brand_BMW',
       'onehot__brand_Chevrolet', 'onehot__brand_Daewoo',
       'onehot__brand_Datsun', 'onehot__brand_Fiat',
       'onehot__brand_Force', 'onehot__brand_Ford', 'onehot__brand_Honda',
       'onehot__brand_Hyundai', 'onehot__brand_Isuzu',
       'onehot__brand_Jaguar', 'onehot__brand_Jeep', 'onehot__brand_Kia',
       'onehot__brand_Land', 'onehot__brand_Lexus', 'onehot__brand_MG',
       'onehot__brand_Mahindra', 'onehot__brand_Maruti',
       'onehot__brand_Mercedes-Benz', 'onehot__brand_Mitsubishi',
       'onehot__brand_Nissan', 'onehot__brand_Opel',
       'onehot__brand_Peugeot', 'onehot__brand_Renault',
       'onehot__brand_Skoda', 'onehot__brand_Tata',
       'onehot__brand_Toyota', 'onehot__brand_Volkswagen',
       'onehot__brand_Volvo', 'onehot__fuel_CNG', 'onehot__fuel_Diesel',
       'onehot__fuel_LPG', 'onehot__fuel_Petrol', 'remainder__km_driven'],
      dtype=object)

In [66]:
transformer.n_features_in_

4

In [67]:
transformer.named_transformers_

{'ordinal': OrdinalEncoder(categories=[['Test Drive Car', 'Fourth & Above Owner',
                             'Third Owner', 'Second Owner', 'First Owner']]),
 'onehot': OneHotEncoder(sparse_output=False),
 'remainder': FunctionTransformer(accept_sparse=True, check_inverse=False,
                     feature_names_out='one-to-one')}

In [69]:
transformer.named_transformers_['ordinal']

OrdinalEncoder(categories=[['Test Drive Car', 'Fourth & Above Owner',
                            'Third Owner', 'Second Owner', 'First Owner']])

In [70]:
transformer.named_transformers_['ordinal'].categories

[['Test Drive Car',
  'Fourth & Above Owner',
  'Third Owner',
  'Second Owner',
  'First Owner']]

In [73]:
transformer.named_transformers_['onehot']

OneHotEncoder(sparse_output=False)

In [68]:
transformer.output_indices_

{'ordinal': slice(0, 1, None),
 'onehot': slice(1, 37, None),
 'remainder': slice(37, 38, None)}

## Sklearn Pipeline

In [5]:
df = pd.read_csv('cars.csv')

In [6]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [7]:
df.shape

(8128, 5)

In [8]:
'''
to make things interesting and just to give a better example for pipeline, we will introduce some 
missing values into the cols -> km_driven and owner
'''

import numpy

np.random.seed(42)
missing_km_indices = np.random.choice(df.index, size=int(0.05 * len(df)), replace=False)
df.loc[missing_km_indices, 'km_driven'] = np.nan

# introduce missing values in 'owner' column (1% missing values)
missing_owner_indices = np.random.choice(df.index, size=int(0.01 * len(df)), replace=False)
df.loc[missing_owner_indices, 'owner'] = np.nan

In [9]:
print(type(missing_km_indices))

<class 'numpy.ndarray'>

In [10]:
'''
df.index
Output:
RangeIndex(start=0, stop=4, step=1)

np.random.choice(df.index, size=50, replace=False)

Meaning:

randomly select 50 row indices from dataframe.

replace=False means:

❌ No duplicates.

Example output:

array([12, 87, 45, 300, 22, 99, ...])

5️⃣ Insert missing values in km_driven
df.loc[missing_km_indices, 'km_driven'] = np.nan

What .loc means

Syntax:

df.loc[row_selection, column_selection]

Here:

rows → missing_km_indices
column → 'km_driven'

Example:

Suppose:

missing_km_indices = [2,5,8]

Then this selects:

index	km_driven
2	5000
5	12000
8	30000
Then we assign:
= np.nan

np.nan means missing value.

So after execution:

index	km_driven
2	NaN
5	NaN
8	NaN
Final effect

5% of rows now have:

km_driven = NaN
'''

"\ndf.index\nOutput:\nRangeIndex(start=0, stop=4, step=1)\n\nnp.random.choice(df.index, size=50, replace=False)\n\nMeaning:\n\nrandomly select 50 row indices from dataframe.\n\nreplace=False means:\n\n❌ No duplicates.\n\nExample output:\n\narray([12, 87, 45, 300, 22, 99, ...])\n\n5️⃣ Insert missing values in km_driven\ndf.loc[missing_km_indices, 'km_driven'] = np.nan\n\nWhat .loc means\n\nSyntax:\n\ndf.loc[row_selection, column_selection]\n\nHere:\n\nrows → missing_km_indices\ncolumn → 'km_driven'\n\nExample:\n\nSuppose:\n\nmissing_km_indices = [2,5,8]\n\nThen this selects:\n\nindex\tkm_driven\n2\t5000\n5\t12000\n8\t30000\nThen we assign:\n= np.nan\n\nnp.nan means missing value.\n\nSo after execution:\n\nindex\tkm_driven\n2\tNaN\n5\tNaN\n8\tNaN\nFinal effect\n\n5% of rows now have:\n\nkm_driven = NaN\n"

In [11]:
df.isnull().sum()

brand              0
km_driven        406
fuel               0
owner             81
selling_price      0
dtype: int64

In [12]:
'''
Plan of Attack

1. Missing Value Imputation
2. Encoding categorical variables
3. Scaling
4. Feature selection
5. Model Building
6. Prediction
'''

'\nPlan of Attack\n\n1. Missing Value Imputation\n2. Encoding categorical variables\n3. Scaling\n4. Feature selection\n5. Model Building\n6. Prediction\n'

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    df.drop(columns=['selling_price']),
    df['selling_price'],
    test_size=0.2,
    random_state=42,
)

In [14]:
X_train.head()

        brand  km_driven    fuel                 owner
6518     Tata     2560.0  Petrol           First Owner
6144    Honda    80000.0  Petrol          Second Owner
6381  Hyundai   150000.0  Diesel  Fourth & Above Owner
438    Maruti   120000.0  Diesel          Second Owner
5939   Maruti    25000.0  Petrol           First Owner

In [15]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6502 entries, 6518 to 7270
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   brand      6502 non-null   object
 1   km_driven  6502 non-null   float64
 2   fuel       6502 non-null   object
 3   owner      6442 non-null   object
dtypes: float64(1), object(3)
memory usage: 254.0+ KB

In [16]:
df['owner'].value_counts()

owner
First Owner             5235
Second Owner            2085
Third Owner              549
Fourth & Above Owner     173
Test Drive Car             5
Name: count, dtype: int64

In [96]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import SelectKBest, chi2

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression

In [97]:
'''
ColumnTransformer([
    (name, transformer, columns)
], remainder=...)


Your case
('scale', MinMaxScaler(), slice(0, 38))

Meaning:

Element	Meaning
scale	        Name of transformation
MinMaxScaler()	Scaling algorithm
slice(0,38)	    Columns 0 → 37

So:
Apply MinMaxScaler to columns 0–37
'''

"\nColumnTransformer([\n    (name, transformer, columns)\n], remainder=...)\n\n\nYour case\n('scale', MinMaxScaler(), slice(0, 38))\n\nMeaning:\n\nElement\tMeaning\nscale\t        Name of transformation\nMinMaxScaler()\tScaling algorithm\nslice(0,38)\t    Columns 0 → 37\n\nSo:\nApply MinMaxScaler to columns 0–37\n"

In [98]:
# imputation transformer

trf1 = ColumnTransformer([
    ('impute_km_driven', SimpleImputer(), [1]),   # default setting -> it replaces the missing value with the mean
    ('impute_owner', SimpleImputer(strategy='most_frequent'), [3]),  # here it replaces with the most frequent/common values -> in our case, it is 'First Owner'
], remainder='passthrough')

In [99]:
'''
https://chatgpt.com/share/69b1442c-bf7c-8008-8c95-720563f5ab20
'''

'\nhttps://chatgpt.com/share/69b1442c-bf7c-8008-8c95-720563f5ab20\n'

In [100]:
X_train.head()

        brand  km_driven    fuel                 owner
6518     Tata     2560.0  Petrol           First Owner
6144    Honda    80000.0  Petrol          Second Owner
6381  Hyundai   150000.0  Diesel  Fourth & Above Owner
438    Maruti   120000.0  Diesel          Second Owner
5939   Maruti    25000.0  Petrol           First Owner

In [101]:
# encoding categorical variables

trf2 = ColumnTransformer([
    ('ordinal', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), [1]),
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False), [2, 3]),
], remainder='passthrough')

In [102]:
# Scaling
# at this stage, we have 38 cols in total -> [0->37]
# also learn about Standard Scaler

trf3 = ColumnTransformer([
    ('scale', MinMaxScaler(), slice(0, 38)),
], remainder='passthrough')

In [103]:
a = [1, 2, 3, 4, 5]
x = slice(0, 4)     # this is a slice object.
print(x)  # we can also try printing -> it is a slice object -> slice(0, 5, None)

'''
start = 0
stop = 4
step = None

The slice object simply stores slicing parameters.

You can check its attributes:

print(x.start)  # 0
print(x.stop)   # 4
print(x.step)   # None

3. Why does slice() exist?

Because sometimes the slice must be stored or passed dynamically.

Example:

def get_part(lst, sl):
    return lst[sl]

a = [1,2,3,4,5]

s = slice(1,4)

print(get_part(a, s))

5. Does a[x] modify the list in-place?

No.

a = [1,2,3,4,5]
x = slice(0,4)

b = a[x]

print(a)
print(b)

Output:

[1,2,3,4,5]
[1,2,3,4]

a[x] returns a new list.

It does NOT modify a in place.

'''


b = a[x]  # this is equivalent to a[0:4]
print(a)
print(b)

slice(0, 4, None)
[1, 2, 3, 4, 5]
[1, 2, 3, 4]

In [104]:
'''
Also, why are we using slice??

2️⃣ What ColumnTransformer Accepts for Column Selection

ColumnTransformer allows multiple ways to specify columns:

Method	Example
List of column indices	[0,1,2]
Single column	[3]
Slice object	slice(0,38)
Column names	['age','salary']
Boolean mask	[True,False,True]

So sklearn allows flexibility.

3️⃣ Why slice(0,38) Is Used Here

At this stage you said:
we have 38 columns -> 0 to 37
Instead of writing:
[0,1,2,3,4,5,6,7....37]
we simply write:
slice(0,38)
Which means:
columns 0 → 37
It is shorter and cleaner.

4️⃣ Could We Use List Instead?
Yes. This would work exactly the same:
trf3 = ColumnTransformer([
    ('scale', MinMaxScaler(), list(range(38))),
], remainder='passthrough')

Because:
list(range(38))
produces
[0,1,2,3,4,5,6,...,37]
But this is less elegant.


9️⃣ Important Subtle Point (Very Useful)
If your data is a pandas DataFrame, you could also do:
('scale', MinMaxScaler(), X.columns)
Which means:
scale all columns
Even better.

'''

"\nAlso, why are we using slice??\n\n2️⃣ What ColumnTransformer Accepts for Column Selection\n\nColumnTransformer allows multiple ways to specify columns:\n\nMethod\tExample\nList of column indices\t[0,1,2]\nSingle column\t[3]\nSlice object\tslice(0,38)\nColumn names\t['age','salary']\nBoolean mask\t[True,False,True]\n\nSo sklearn allows flexibility.\n\n3️⃣ Why slice(0,38) Is Used Here\n\nAt this stage you said:\nwe have 38 columns -> 0 to 37\nInstead of writing:\n[0,1,2,3,4,5,6,7....37]\nwe simply write:\nslice(0,38)\nWhich means:\ncolumns 0 → 37\nIt is shorter and cleaner.\n\n4️⃣ Could We Use List Instead?\nYes. This would work exactly the same:\ntrf3 = ColumnTransformer([\n    ('scale', MinMaxScaler(), list(range(38))),\n], remainder='passthrough')\n\nBecause:\nlist(range(38))\nproduces\n[0,1,2,3,4,5,6,...,37]\nBut this is less elegant.\n\n\n9️⃣ Important Subtle Point (Very Useful)\nIf your data is a pandas DataFrame, you could also do:\n('scale', MinMaxScaler(), X.columns)\nWhich means:\nscale all columns\nEven better.\n\n"

In [105]:
# Feature Selection
# columns transformer not needed, we can use also.
trf4 = SelectKBest(score_func=chi2, k=10)

In [127]:
# Train the model
trf5 = RandomForestRegressor()
# trf5 = LinearRegression()

In [128]:
from sklearn.pipeline import Pipeline

pipe = Pipeline([
    ('imputer', trf1),
    ('encoder', trf2),
    ('scaler', trf3),
    ('fselector', trf4),
    ('model', trf5),
])

### Important rule:

ColumnTransformer outputs transformed columns first, then remainder columns. -> So the order of indices
will keep changing

In [129]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('imputer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_km_driven',
                                                  SimpleImputer(), [1]),
                                                 ('impute_owner',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [3])])),
                ('encoder',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ordinal',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  [1]),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [2, 3])])),
                ('scaler',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 38, None))])),
                ('fselector',
                 SelectKBest(score_func=<function chi2 at 0x000001D18759AB90>)),
                ('model', RandomForestRegressor())])

In [130]:
pipe.feature_names_in_

array(['brand', 'km_driven', 'fuel', 'owner'], dtype=object)

In [131]:
pipe.named_steps

{'imputer': ColumnTransformer(remainder='passthrough',
                   transformers=[('impute_km_driven', SimpleImputer(), [1]),
                                 ('impute_owner',
                                  SimpleImputer(strategy='most_frequent'),
                                  [3])]),
 'encoder': ColumnTransformer(remainder='passthrough',
                   transformers=[('ordinal',
                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                 unknown_value=-1),
                                  [1]),
                                 ('onehot',
                                  OneHotEncoder(handle_unknown='ignore',
                                                sparse_output=False),
                                  [2, 3])]),
 'scaler': ColumnTransformer(remainder='passthrough',
                   transformers=[('scale', MinMaxScaler(), slice(0, 38, None))]),
 'fselector': SelectKBest(score_func=<function chi2 at 0x000001D18759AB90>),
 'model': RandomForestRegressor()}

In [132]:
pipe['imputer'].transformers_[0][1].statistics_

array([70050.98323593])

In [133]:
pipe.named_steps['imputer'].transformers_[0][1].statistics_

array([70050.98323593])

In [134]:
# # imputation transformer

# trf1 = ColumnTransformer([
#     ('impute_km_driven', SimpleImputer(), [1]),   # default setting -> it replaces the missing value with the mean
#     ('impute_owner', SimpleImputer(strategy='most_frequent'), [3]),  # here it replaces with the most frequent/common values -> in our case, it is 'First Owner'
# ], remainder='passthrough')

pipe.named_steps['imputer'].transformers_[0][1].statistics_

array([70050.98323593])

In [135]:
pipe.named_steps['scaler'].transformers_[0][1].data_max_

array([4.000000e+00, 1.000000e+00, 1.000000e+00, 1.000000e+00,
       1.000000e+00, 1.000000e+00, 1.000000e+00, 1.000000e+00,
       1.000000e+00, 1.000000e+00, 1.000000e+00, 1.000000e+00,
       1.000000e+00, 1.000000e+00, 1.000000e+00, 1.000000e+00,
       1.000000e+00, 1.000000e+00, 1.000000e+00, 1.000000e+00,
       1.000000e+00, 1.000000e+00, 1.000000e+00, 1.000000e+00,
       1.000000e+00, 1.000000e+00, 1.000000e+00, 1.000000e+00,
       1.000000e+00, 1.000000e+00, 1.000000e+00, 1.000000e+00,
       1.000000e+00, 1.000000e+00, 1.000000e+00, 1.000000e+00,
       1.000000e+00, 2.360457e+06])

In [136]:
pipe.predict(X_test)[10: 40]

array([ 490588.0249845 ,  490588.0249845 ,  490588.0249845 ,
        490588.0249845 ,  490588.0249845 ,  490588.0249845 ,
        490588.0249845 ,  490588.0249845 ,  490588.0249845 ,
        490588.0249845 ,  490588.0249845 ,  490588.0249845 ,
       2910321.21666828,  490588.0249845 ,  490588.0249845 ,
        490588.0249845 ,  490588.0249845 , 3321536.43611775,
        490588.0249845 ,  490588.0249845 ,  490588.0249845 ,
        490588.0249845 ,  490588.0249845 ,  490588.0249845 ,
        490588.0249845 ,  490588.0249845 ,  490588.0249845 ,
        490588.0249845 ,  490588.0249845 ,  490588.0249845 ])

In [137]:
'''
### Your current approach works, but it has three major problems:

1️⃣ Column indices keep changing
2️⃣ Hardcoding slice(0,38) is fragile
3️⃣ Multiple ColumnTransformers make debugging harder

The better design is:

ONE ColumnTransformer with small pipelines inside it

This avoids index shifting completely.

⭐ Professional Pipeline Structure

Instead of:

Imputer → Encoder → Scaler → FeatureSelector → Model

we build column-wise pipelines.

                ColumnTransformer
               /        |        \
        numeric      owner      categorical
         pipeline    pipeline      pipeline
            |           |              |
       impute+scale  impute+ord    onehot

Then attach model.

Step 1 — Define column groups

Since your dataset is:

column	type
company	categorical
km_driven	numeric
fuel	categorical
owner	ordinal categorical
num_cols = [1]        # km_driven
owner_col = [3]       # owner
cat_cols = [0,2]      # company, fuel
Step 2 — Create small pipelines
Numeric pipeline
num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', MinMaxScaler())
])
Owner pipeline (ordinal)
owner_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('ordinal', OrdinalEncoder())
])
Categorical pipeline
cat_pipeline = Pipeline([
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])
Step 3 — Combine them
preprocessor = ColumnTransformer([
    ('num', num_pipeline, num_cols),
    ('owner', owner_pipeline, owner_col),
    ('cat', cat_pipeline, cat_cols)
])

Now sklearn automatically handles:

imputation

encoding

scaling

without column index shifting.

Step 4 — Full pipeline
pipe = Pipeline([
    ('preprocess', preprocessor),
    ('feature_select', SelectKBest(chi2, k=10)),
    ('model', RandomForestRegressor())
])

Then:

pipe.fit(X_train, y_train)
⭐ Why this approach is better
Your Approach	Professional Approach
Multiple ColumnTransformers	Single ColumnTransformer
Indices change after each step	Indices never change
Hardcoded slice(0,38)	No guessing columns
Harder debugging	Very clean structure
⭐ Even Better (automatic column detection)

If your dataset grows, you can automatically detect column types.

num_cols = X.select_dtypes(include=['int64','float64']).columns
cat_cols = X.select_dtypes(include=['object']).columns

This is very common in real ML projects.

⭐ Bonus: Debugging trick

You can inspect the transformed dataset:

pipe.named_steps['preprocess'].fit_transform(X_train)

or feature names:

pipe.named_steps['preprocess'].get_feature_names_out()
⭐ Important ML Interview Concept

This pipeline automatically prevents data leakage.

Without pipelines people accidentally do:

imputer.fit(X)
scaler.fit(X)
train_test_split()

Which leaks test data statistics into training.

Pipelines ensure:

fit only on training data
apply to test data

This is one of the main reasons sklearn pipelines exist.

✅ Since you're learning ML pipelines deeply, the next very powerful concept you should know is:

'''

"\n### Your current approach works, but it has three major problems:\n\n1️⃣ Column indices keep changing\n2️⃣ Hardcoding slice(0,38) is fragile\n3️⃣ Multiple ColumnTransformers make debugging harder\n\nThe better design is:\n\nONE ColumnTransformer with small pipelines inside it\n\nThis avoids index shifting completely.\n\n⭐ Professional Pipeline Structure\n\nInstead of:\n\nImputer → Encoder → Scaler → FeatureSelector → Model\n\nwe build column-wise pipelines.\n\n                ColumnTransformer\n               /        |                numeric      owner      categorical\n         pipeline    pipeline      pipeline\n            |           |              |\n       impute+scale  impute+ord    onehot\n\nThen attach model.\n\nStep 1 — Define column groups\n\nSince your dataset is:\n\ncolumn\ttype\ncompany\tcategorical\nkm_driven\tnumeric\nfuel\tcategorical\nowner\tordinal categorical\nnum_cols = [1]        # km_driven\nowner_col = [3]       # owner\ncat_cols = [0,2]      # company, fuel\nStep 2 — Create small pipelines\nNumeric pipeline\nnum_pipeline = Pipeline([\n    ('imputer', SimpleImputer(strategy='mean')),\n    ('scaler', MinMaxScaler())\n])\nOwner pipeline (ordinal)\nowner_pipeline = Pipeline([\n    ('imputer', SimpleImputer(strategy='most_frequent')),\n    ('ordinal', OrdinalEncoder())\n])\nCategorical pipeline\ncat_pipeline = Pipeline([\n    ('onehot', OneHotEncoder(handle_unknown='ignore'))\n])\nStep 3 — Combine them\npreprocessor = ColumnTransformer([\n    ('num', num_pipeline, num_cols),\n    ('owner', owner_pipeline, owner_col),\n    ('cat', cat_pipeline, cat_cols)\n])\n\nNow sklearn automatically handles:\n\nimputation\n\nencoding\n\nscaling\n\nwithout column index shifting.\n\nStep 4 — Full pipeline\npipe = Pipeline([\n    ('preprocess', preprocessor),\n    ('feature_select', SelectKBest(chi2, k=10)),\n    ('model', RandomForestRegressor())\n])\n\nThen:\n\npipe.fit(X_train, y_train)\n⭐ Why this approach is better\nYour Approach\tProfessional Approach\nMultiple ColumnTransformers\tSingle ColumnTransformer\nIndices change after each step\tIndices never change\nHardcoded slice(0,38)\tNo guessing columns\nHarder debugging\tVery clean structure\n⭐ Even Better (automatic column detection)\n\nIf your dataset grows, you can automatically detect column types.\n\nnum_cols = X.select_dtypes(include=['int64','float64']).columns\ncat_cols = X.select_dtypes(include=['object']).columns\n\nThis is very common in real ML projects.\n\n⭐ Bonus: Debugging trick\n\nYou can inspect the transformed dataset:\n\npipe.named_steps['preprocess'].fit_transform(X_train)\n\nor feature names:\n\npipe.named_steps['preprocess'].get_feature_names_out()\n⭐ Important ML Interview Concept\n\nThis pipeline automatically prevents data leakage.\n\nWithout pipelines people accidentally do:\n\nimputer.fit(X)\nscaler.fit(X)\ntrain_test_split()\n\nWhich leaks test data statistics into training.\n\nPipelines ensure:\n\nfit only on training data\napply to test data\n\nThis is one of the main reasons sklearn pipelines exist.\n\n✅ Since you're learning ML pipelines deeply, the next very powerful concept you should know is:\n\n"

In [138]:
'''
preprocessor = ColumnTransformer([
    
    ('num', Pipeline([
        ('imputer', SimpleImputer()),
        ('scaler', MinMaxScaler())
    ]), [1]),

    ('owner', Pipeline([
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('ordinal', OrdinalEncoder())
    ]), [3]),

    ('cat', OneHotEncoder(handle_unknown='ignore'), [0,2])

])

pipe = Pipeline([
    ('preprocess', preprocessor),
    ('feature', SelectKBest(chi2, k=10)),
    ('model', RandomForestRegressor())
])
'''

"\npreprocessor = ColumnTransformer([\n    \n    ('num', Pipeline([\n        ('imputer', SimpleImputer()),\n        ('scaler', MinMaxScaler())\n    ]), [1]),\n\n    ('owner', Pipeline([\n        ('imputer', SimpleImputer(strategy='most_frequent')),\n        ('ordinal', OrdinalEncoder())\n    ]), [3]),\n\n    ('cat', OneHotEncoder(handle_unknown='ignore'), [0,2])\n\n])\n\npipe = Pipeline([\n    ('preprocess', preprocessor),\n    ('feature', SelectKBest(chi2, k=10)),\n    ('model', RandomForestRegressor())\n])\n"

In [139]:
'''
8️⃣ Another important problem you will soon hit

You used:

SelectKBest(score_func=chi2)

But chi² only works with non-negative values.

So if you used:

StandardScaler

(which produces negative values)

you would get another error.

That's why:

chi2 + MinMaxScaler works
chi2 + StandardScaler fails

9️⃣ A debugging trick (very useful)

Whenever pipelines break, print intermediate output:

pipe[:-1].fit_transform(X_train)

or step-by-step:

X1 = trf1.fit_transform(X_train)
X2 = trf2.fit_transform(X1)

This helps see column order changes.
'''

"\n8️⃣ Another important problem you will soon hit\n\nYou used:\n\nSelectKBest(score_func=chi2)\n\nBut chi² only works with non-negative values.\n\nSo if you used:\n\nStandardScaler\n\n(which produces negative values)\n\nyou would get another error.\n\nThat's why:\n\nchi2 + MinMaxScaler works\nchi2 + StandardScaler fails\n\n9️⃣ A debugging trick (very useful)\n\nWhenever pipelines break, print intermediate output:\n\npipe[:-1].fit_transform(X_train)\n\nor step-by-step:\n\nX1 = trf1.fit_transform(X_train)\nX2 = trf2.fit_transform(X1)\n\nThis helps see column order changes.\n"

### Cross Validation

In [140]:
# cross validation using cross_val_score

from sklearn.model_selection import cross_val_score
cross_val_score(pipe, X_train, y_train, cv=5, scoring='neg_mean_squared_error').mean()

np.float64(-228330717983.9349)

### Hyperparameter Tuning

In [141]:
# gridsearchcv
params = {
    'model__max_depth': [1, 2, 3, 4, 5, None]
}

In [142]:
from sklearn.model_selection import GridSearchCV

grid = GridSearchCV(pipe, params, cv=5, scoring='neg_mean_squared_error')
grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('imputer',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('impute_km_driven',
                                                                         SimpleImputer(),
                                                                         [1]),
                                                                        ('impute_owner',
                                                                         SimpleImputer(strategy='most_frequent'),
                                                                         [3])])),
                                       ('encoder',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('ordinal',
                                                                         OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                                        unknow...
                                                                         OneHotEncoder(handle_unknown='ignore',
                                                                                       sparse_output=False),
                                                                         [2,
                                                                          3])])),
                                       ('scaler',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('scale',
                                                                         MinMaxScaler(),
                                                                         slice(0, 38, None))])),
                                       ('fselector',
                                        SelectKBest(score_func=<function chi2 at 0x000001D18759AB90>)),
                                       ('model', RandomForestRegressor())]),
             param_grid={'model__max_depth': [1, 2, 3, 4, 5, None]},
             scoring='neg_mean_squared_error')

In [143]:
grid.best_score_

np.float64(-228385042379.5895)

In [144]:
grid.best_params_

{'model__max_depth': None}

### Export Pipeline

In [ ]:
# export

import pickle
pickle.dump(pipe, open('pipe.pkl', 'wb'))